FROM python:3.11-slim
WORKDIR /programming/aaaaaa


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


COPY main.py .
EXPOSE 8085
CMD ["python", "main.py"]